#define global variable
#incase we want to change it we could do it

units:
  #Proxy Spacing Variable
  kx: u
  ky: u

  #Pading Variable
  px: kx + 4
  py: ky + 4

points:
  key.tags:
    - normal
  rotate: 7
  zones:
    matrix:
      anchor.shift: [100,-100]
      key.padding: ky
      key.spread: kx
      columns:
        pinky:
          rows:
            home.shift: [0,0]
            top.shift: [0,0]
          key:
            shift: [-2,0]
            column_net: P21
        ring:
          key:
            stagger: 12
            splay: -7
            column_net: P20
        middle:
          key:
            stagger: kx/3
            column_net: P19

        index:
          key:
            stagger: -kx/3
            column_net: P18
        reach:
          key:
            stagger: -kx/6
            column_net: P15
      rows:
        bottom:
          row_net: P10
        home:
          row_net: P16
        top:
          row_net: P14
    thumb_fan:
      key.padding: ky
      key.spread: kx
      anchor:
        ref: matrix_index_bottom
        shift : [.5kx,-1.167kx]
      columns:
        inner:
          key.column_net: P19
        middle:
          key:
            splay: 60
            shift: [.3kx,-.32kx]
            width: 2kx
            column_net: P18
            tags:
              - long
        reach:
          key:
            shift: [-.7kx,-1.32kx]
            width: 2kx
            column_net: P15
            tags:
              - long
      rows:
        cluster:
          row_net: P9

outlines:  
  raw:
    - what: rectangle
      where: true
      size: [kx,ky]  
  board:
    - what: polygon
      operation: stack
      points:
      - ref: matrix_pinky_top
        shift: [-0.7kx,0.5kx]
      - ref: matrix_ring_top
        shift: [0,kx]
      - ref: matrix_index_top
        shift: [0,kx]
      - ref: matrix_reach_top
        shift: [0.5kx,0.7kx]
      - ref: matrix_reach_top
        shift: [1.86kx,0.7kx]
      - ref: matrix_reach_bottom
        shift: [1.86kx,-.05kx]
      - ref: thumb_fan_reach_cluster
        shift: [1.18kx,-.65kx]
      - ref: thumb_fan_reach_cluster
        shift: [-1.15kx,-.65kx]
      - ref: thumb_fan_inner_cluster
        shift: [.5kx,-.7kx]
      - ref: matrix_pinky_bottom
        shift: [-.7kx,-.6kx]
      fillet: 4
  keys:
    - what: rectangle
      where: [normal]
      size: [kx-.5,ky-.5]
  keycaps2:
    - what: rectangle
      where: [long]
      size: [2kx-.5,ky-.5]

  preview:
    [keys,keycaps2]

  combo:
    - name: board
    - operation: subtract
      name: preview

pcbs:
  flipper:
    outlines:
      - outline: preview
        layer: Eco1.User
      - outline: board
      
    footprints:
      sw_hs:
        what: mx
        where: true
        params:
          keycaps: true
          reverse: true
          hotswap: true
          from: "{{column_net}}"
          to: "{{colrow}}"
      sw:
        what: mx
        where: true
        adjust.rotate: 180
        params:
          keycaps: true
          reverse: true
          from: "{{column_net}}"
          to: "{{colrow}}"
      diode:
        what: diode
        where: true
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [0, -.435kx]

      # opt_sw:
      #   what: mx
      #   where:
      #     ref: thumb_fan_middle_cluster
      #     shift: [.5kx,0]
        #   adjust.rotate: 180
      #   params:
      #     keycaps: true
      #     reverse: true
      #     from: P18
      #     to: middle_cluster
      # opt_sw_hs:
      #   what: mx
      #   where:
      #     ref: thumb_fan_middle_cluster
      #     shift: [.5kx,0]
      #   params:
      #     keycaps: true
      #     reverse: true
      #     hotswap: true
      #     from: P18
      #     to: middle_cluster
      #

      promicro:
        what: nicenano
        where:
          ref: matrix_reach_top
          shift: [0.85px,-0.21px]
        params:
          reversible: true
          include_traces: true
      jst:
        what: jst
        where:
          ref: matrix_reach_top
          shift: [1.7kx,-1.4kx]
          rotate : -90
        params:
          reversible: true
      pwr:
        what: power_switch
        where:
          ref: matrix_reach_top
          shift: [1.75kx,-.3kx]
        params:
          reversible: true
          from: BAT_P
          to: RAW
      rst:
        what: reset_switch
        where:
          ref: matrix_reach_top
          shift: [1.75kx,.4kx]
          rotate: 90
        params:
          reversible: true

      pimoroni:
        what: pimoroni
        adjust.rotate: -90
        where:
          ref: matrix_middle_bottom
          shift: [.25kx,-.65ky]


