#define global variable
#incase we want to change it we could do it

units:
  #Proxy Spacing Variable
  kx: u
  ky: u

  #Pading Variable
  px: kx + 4
  py: ky + 4

points:
  key.tags:
    - normal
  rotate: 7
  zones:
    matrix:
      anchor.shift: [100,-100]
      key.padding: ky
      key.spread: kx
      columns:
        pinky:
          rows:
            home.shift: [0,0]
            top.shift: [0,0]
          key:
            shift: [-2,0]
            column_net: P21
        ring:
          key:
            stagger: 12
            splay: -7
            column_net: P20
        middle:
          key:
            stagger: kx/3
            column_net: P19

        index:
          key:
            stagger: -kx/3
            column_net: P18
        reach:
          key:
            stagger: -kx/6
            column_net: P15
      rows:
        bottom:
          row_net: P10
        home:
          row_net: P16
        top:
          row_net: P14
    thumb_fan:
      key.padding: ky
      key.spread: kx
      anchor:
        ref: matrix_index_bottom
        shift : [.5kx,-1.167kx]
      columns:
        inner:
          key.column_net: P19
        middle:
          key:
            splay: 60
            shift: [.3kx,-.32kx]
            width: 2kx
            column_net: P18
            tags:
              - long
        reach:
          key:
            shift: [-.7kx,-1.32kx]
            width: 2kx
            column_net: P15
            tags:
              - long
      rows:
        cluster:
          row_net: P9

outlines:  
  board:
    - what: polygon
      operation: stack
      points:
      - ref: matrix_pinky_top
        shift: [-0.7kx,0.5kx]
      - ref: matrix_ring_top
        shift: [0,kx]
      - ref: matrix_index_top
        shift: [0,kx]
      - ref: matrix_reach_top
        shift: [0.5kx,0.7kx]
      - ref: matrix_reach_top
        shift: [1.86kx,0.7kx]
      - ref: matrix_reach_bottom
        shift: [1.86kx,-.05kx]
      - ref: thumb_fan_reach_cluster
        shift: [1.18kx,-.65kx]
      - ref: thumb_fan_reach_cluster
        shift: [-1.15kx,-.65kx]
      - ref: thumb_fan_inner_cluster
        shift: [.5kx,-.7kx]
      - ref: matrix_pinky_bottom
        shift: [-.7kx,-.6kx]
      fillet: 4
  _keys:
    - what: rectangle
      where: [normal]
      size: [kx-.5,ky-.5]
  _keys2:
    - what: rectangle
      where: [long]
      size: [2kx-.5,ky-.5]

  _preview:
    [_keys,_keys2]

  combo:
    - name: board
    - operation: subtract
      name: _preview

  _mcu_footprint:
    - what: rectangle
      where:
        ref: matrix_reach_top
        shift: [1.4kx+3.5,0]
      size: [37,78]

  _pf:
    - what: rectangle
      where:
        ref: matrix_middle_bottom
        shift: [0,-21.85]
      size: [27,24]

  _switch_cutout:
    - what: rectangle
      where: true
      size: 14
      bound: false

  _pimoroni_footprint:
    [_pf,-_preview]

  _bigger_board:
    - what: outline
      name: board
      expand: 6

  _cage_holes:
    - what: circle
      radius: 1.2
      where:
        ref: matrix_pinky_home
        shift: [-.8kx,1.54kx]
    - what: circle
      radius: 1.2
      where:
        ref: matrix_pinky_home
        shift: [-.75kx,-1.7kx]
    - what: circle
      radius: 1.2
      where:
        ref: matrix_middle_bottom
        shift: [0,-2.17kx]
    - what: circle
      radius: 1.2
      where:
        ref: matrix_middle_top
        shift: [0,.8kx]
    - what: circle
      radius: 1.2
      where:
        ref: matrix_reach_top
        shift: [.4kx,.88ky]

    - what: circle
      radius: 1.2
      where:
        ref: thumb_fan_inner_cluster
        shift: [.45kx,-.86ky]

    - what: circle
      radius: 1.2
      where:
        ref: thumb_fan_reach_cluster
        shift: [-1.2kx,-.7ky]

    - what: circle
      radius: 1.2
      where:
        ref: thumb_fan_reach_cluster
        shift: [1.2kx,-.7ky]

  preview:
    [_bigger_board,-board,_preview,-_cage_holes]
  
  plate:
    [_bigger_board,-_switch_cutout,-_mcu_footprint,-_pimoroni_footprint,-_cage_holes]
  
  _mounting_holes:
    - what: circle
      radius: 1.2
      where:
        ref: matrix_pinky_top
        shift: [.6kx,.8ky]

    - what: circle
      radius: 1.2
      where:
        ref: matrix_reach_top
        shift: [1.71kx,0]

    - what: circle
      radius: 1.2
      where:
        ref: thumb_fan_reach_cluster
        shift: [.7kx,0]
    
    - what: circle
      radius: 1.2
      where:
        ref: matrix_ring_bottom
        shift: [0,-ky]

    - what: circle 
      radius: 1.2
      where:
        ref: matrix_middle_home
        shift: [.5kx,-.5ky]

  backplate:
    [_bigger_board,-_mounting_holes,-_cage_holes]
    
        


      

pcbs:
  flippie:
    outlines:
      - outline: preview
        layer: Eco1.User
      - outline: board
      
    footprints:
      sw_hs:
        what: mx
        where: true
        params:
          keycaps: true
          reverse: true
          hotswap: true
          from: "{{column_net}}"
          to: "{{colrow}}"
      sw:
        what: mx
        where: true
        adjust.rotate: 180
        params:
          keycaps: true
          reverse: true
          from: "{{column_net}}"
          to: "{{colrow}}"

      diode:
        what: diode
        where: true
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [0, -.435kx]

      mcu:
        what: nicenano
        where:
          ref: matrix_reach_top
          shift: [1.08kx,-0.19px]
        params:
          reversible: true
          include_traces: true

      display:
        what: oled
        where:
          ref: matrix_reach_bottom
          shift: [1.08kx,1.5kx]
        params:
          reversible: true
          include_traces: true
          SDA: P2
          SCL: P3
          
      jst:
        what: jst
        where:
          ref: matrix_reach_top
          shift: [1.7kx,-1.7kx]
          rotate : -90
        params:
          reversible: true
      pwr:
        what: power_switch
        where:
          ref: matrix_reach_top
          shift: [1.75kx,-1.2kx]
        params:
          reversible: true
          from: BAT_P
          to: RAW
      rst:
        what: reset_switch
        where:
          ref: matrix_reach_top
          shift: [1.72kx,.4kx]
          rotate: 90
        params:
          reversible: true

      pimoroni:
        what: pimoroni
        adjust.rotate: -90
        where:
          ref: matrix_middle_bottom
          shift: [.25kx,-.65ky]

      h1:
        what: mountinghole
        where:
          ref: matrix_pinky_top
          shift: [.6kx,.8ky]
      h2:
        what: mountinghole
        where:
          ref: matrix_reach_top
          shift: [1.71kx,0]
      h3:
        what: mountinghole
        where:
          ref: thumb_fan_reach_cluster
          shift: [.7kx,0]
      h4:
        what: mountinghole
        where:
          ref: matrix_ring_bottom
          shift: [0,-ky]
      h5:
        what: mountinghole
        where:
          ref: matrix_middle_home
          shift: [.5kx,-.5ky]
